#!/usr/bin/env python3
import os
import re
import subprocess
import xml.etree.ElementTree as ET
from xml.dom import minidom

TARGET_DIR = "/Users/fernandavitorino/metrixmidia-site"

def get_git_lastmod(file_path):
    try:
        git_date = subprocess.check_output(
            ["git", "log", "-1", "--format=%cs", "--", file_path],
            cwd=TARGET_DIR
        ).decode('utf-8').strip()
        return git_date if git_date else None
    except Exception:
        return None

def main():
    print("Generating sitemap.xml...")
    urls = []
    
    for root, dirs, files in os.walk(TARGET_DIR):
        if any(d in root for d in [".git", ".vercel", "node_modules", "scripts", "interno"]):
            continue
        for file in files:
            if not file.endswith(".html"):
                continue
            rel_path = os.path.relpath(os.path.join(root, file), TARGET_DIR)
            
            # Skip 404
            if rel_path == "404.html":
                continue
                
            # Exclude files with noindex robots tag
            with open(os.path.join(root, file), 'r', encoding='utf-8') as f:
                content = f.read()
            if 'name="robots" content="noindex"' in content or 'name="robots" content="noindex, nofollow"' in content:
                print(f"  Skipping noindex page: {rel_path}")
                continue
                
            # Build URL path
            if rel_path == "index.html":
                loc = "https://metrixmidia.com.br/"
            elif rel_path.endswith("/index.html"):
                loc = f"https://metrixmidia.com.br/{os.path.dirname(rel_path)}/"
            else:
                loc = f"https://metrixmidia.com.br/{rel_path.replace('.html', '')}/"
                
            # Lastmod from git
            lastmod = get_git_lastmod(rel_path)
            if not lastmod:
                lastmod = "2026-07-29" # default fallback
                
            # Priority and changefreq conventions
            if rel_path == "index.html":
                priority = "1.00"
                changefreq = "daily"
            elif rel_path.startswith("blog/") or rel_path.startswith("case/"):
                priority = "0.80"
                changefreq = "weekly"
            else:
                priority = "0.60"
                changefreq = "monthly"
                
            urls.append({
                "loc": loc,
                "lastmod": lastmod,
                "changefreq": changefreq,
                "priority": priority
            })

    # Sort URLs alphabetically to ensure deterministic generation
    urls.sort(key=lambda x: x["loc"])

    # Build XML
    urlset = ET.Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")
    for url_data in urls:
        url_el = ET.SubElement(urlset, "url")
        ET.SubElement(url_el, "loc").text = url_data["loc"]
        ET.SubElement(url_el, "lastmod").text = url_data["lastmod"]
        ET.SubElement(url_el, "changefreq").text = url_data["changefreq"]
        ET.SubElement(url_el, "priority").text = url_data["priority"]

    # Format XML beautifully
    xmlstr = ET.tostring(urlset, encoding='utf-8')
    parsed = minidom.parseString(xmlstr)
    pretty_xml = parsed.toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")
    
    # Clean up empty lines generated by toprettyxml on some platforms
    pretty_xml = re.sub(r'\n\s*\n', '\n', pretty_xml)

    sitemap_path = os.path.join(TARGET_DIR, "sitemap.xml")
    with open(sitemap_path, "w", encoding="utf-8") as f:
        f.write(pretty_xml)
        
    print(f"Sitemap successfully generated with {len(urls)} URLs at {sitemap_path}")

if __name__ == "__main__":
    main()
